### ISSUE TITLE
Only installs theme for admin side

### ISSUE THREAD

**Issue by k3lux** [WeLikeToCodeStuff/ptero-1.0-theme-install#1]
Hey, so i tried installing the dark n purple theme for my panel, however it only installs for the admin side and not the user. Any idea why? Thanks in advance.

**Comment by Tydium** [comment]
Yeah I can confirm that for Dark N Purple this happens. Im gonna try a the others and try it out.

**Comment by DeveloperNeon** [comment]
Will fix
