### ISSUE TITLE
Some themes are the exact same?

### ISSUE THREAD

**Issue by Tydium** [WeLikeToCodeStuff/ptero-1.0-theme-install#3]
Dracula, Enola, and Twilight feel and look the exact same. I don't know if its me. I did do a hard refresh everytime I installed and uninstalled to be sure. Dark and purple seems to be the only one that is different.

**Comment by DeveloperNeon** [comment]
I think the backgrounds are the same, But tell me if im wrong

**Comment by DeveloperNeon** [comment]
They look the same, Ill ask Oreo about that.
